# Generated by Django 4.2.2 on 2023-06-26 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_stud',
            name='Age',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tbl_stud',
            name='Mark',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
